version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - chvp
  groups:
    sentry:
      patterns:
        - "sentry-*"
    rubocop:
      patterns:
        - "rubocop*"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - chvp
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "08:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  reviewers:
  - chvp
